image:
  file: .gitpod.Dockerfile
tasks:
  - init: echo 'PATH_add /home/gitpod/julia-1.8.0/bin' > /workspace/.envrc \
          && echo 'PATH_add /home/gitpod/julia-1.8.0/bin' > /workspace/.envrc \
          && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> /workspace/.envrc \
          && cd /workspace ; direnv allow .
